dist: xenial

language: python

python:
- "3.6"

env:
  - MOZ_HEADLESS=1

addons:
  firefox: latest
  apt:
    packages:
      - python3-pip

services:
  - docker

install:
  - pip install selenium
  - pip install kazoo
  - pip install pytest
  - pip install pytest-httpserver

before_install:
  - docker run -d zookeeper
  - docker build -t rbmd .
  - docker run -d --network="host" rbmd
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz
  - tar -xvf geckodriver-v0.21.0-linux64.tar.gz
  - export PATH=$PATH:$PWD

script:
  - PYTEST_HTTPSERVER_PORT=9076 py.test -s test/selenium_tests.py
